name: circular_menu_example
version: 0.1.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  circular_menu:
    path: ../
  animated_bottom_navigation_bar:
    git:
      url: https://github.com/rashmisridar/animated-bottom-navigation-bar-flutter.git

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/.
