name: circular_menu
description:  A simple animated circular menu for Flutter, Adjustable radius, colors, alignment, animation curve and animation duration.
version: 1.1.2
author: Hasan Mohammed <hasanmohammed.hm1@gmail.com>
homepage: https://github.com/hasan-hm1/circular_menu

environment:
  #  sdk: ">=2.8.0 <3.0.0"
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_bottom_navigation_bar:
    git:
      url: https://github.com/rashmisridar/animated-bottom-navigation-bar-flutter.git
  flutter_svg: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

